services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - maildev
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=cv_builder_db
      - MAILDEV_HOST=maildev
      - MAILDEV_PORT=1025
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cv_builder_db
    ports:
      - "3307:3306" # Container port 3306 mapped to host port 3307
    volumes:
    - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pexample"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
      - "1025:25"

volumes:
  db_data:
  frontend_node_modules:

networks:
  default:
    driver: bridge